# Generated by Django 4.2.7 on 2023-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
